services:
  mysql:
    image: mysql:latest
    container_name: is-mysql-new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root.1234
      MYSQL_DATABASE: proyecto1
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  albums-api:
    build: .
    container_name: proyecto1-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proyecto1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root.1234
    ports:
      - "8081:8080"